vim.api.nvim_set_keymap("n", "<leader>ll", ":Ex<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "Q", "<nop>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>`", ":b#<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-d>", "<C-d>zz", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-u>", "<C-u>zz", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>s", ":w<cr>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>li", ":LspInfo<cr>", { noremap = true, silent = true })
