format = """
$fill $deno $nodejs $golang
$username\
$hostname\
$localip\
$directory\
$direnv\
$fill\
$docker_context\
$cmd_duration\
$git_metrics\
$git_branch\
$line_break\
$custom\
$character"""

palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[username]
show_always = true
format = '[╭─](lavender)[$user[@](bold surface2)]($style)'
style_user = 'bold green'
style_root = 'bold red'

[character]
format = '[╰─](lavender)$symbol '
success_symbol = '[](lavender) '

[hostname]
ssh_only = false
format = '[$hostname]($style) '
style = 'bold rosewater'

[golang]
symbol = ''
format = '( [$symbol $version( on $mod_version)]($style))'

[deno]
symbol = ''
format = '( [$symbol $version]($style))'

[nodejs]
symbol = ''
format = '( [$symbol $version]($style))'

[fill]
symbol = ' '

[directory]
style = 'bold blue'

[git_metrics]
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[direnv]
disabled = false
